import { jsPDF } from "jspdf";


const DISCLAIMER =
  "This report was generated by an academic AI classification system. " +
  "It is not a medical diagnosis and should not replace evaluation by " +
  "a qualified healthcare professional.";


const formatClassName = (className) => {
  if (!className) {
    return "Unavailable";
  }

  if (className.toLowerCase() === "covid19") {
    return "COVID-19";
  }

  return (
    className.charAt(0).toUpperCase() +
    className.slice(1)
  );
};


const loadImageAsDataUrl = (file) => {
  return new Promise((resolve, reject) => {
    if (!file) {
      resolve(null);
      return;
    }

    const reader = new FileReader();

    reader.onload = () => {
      resolve(reader.result);
    };

    reader.onerror = () => {
      reject(
        new Error(
          "Unable to read the uploaded X-ray image."
        )
      );
    };

    reader.readAsDataURL(file);
  });
};


const getImageDimensions = (
  imageData,
  maxWidth,
  maxHeight
) => {
  return new Promise((resolve, reject) => {
    const image = new Image();

    image.onload = () => {
      const ratio = Math.min(
        maxWidth / image.width,
        maxHeight / image.height
      );

      resolve({
        width: image.width * ratio,
        height: image.height * ratio,
      });
    };

    image.onerror = () => {
      reject(
        new Error(
          "Unable to calculate image dimensions."
        )
      );
    };

    image.src = imageData;
  });
};


export const generatePredictionReport = async ({
  prediction,
  selectedFile,
  user,
}) => {
  if (!prediction) {
    throw new Error(
      "Prediction result is required to generate the report."
    );
  }

  const pdf = new jsPDF({
    orientation: "portrait",
    unit: "mm",
    format: "a4",
  });

  const pageWidth =
    pdf.internal.pageSize.getWidth();

  const pageHeight =
    pdf.internal.pageSize.getHeight();

  const margin = 18;

  const contentWidth =
    pageWidth - margin * 2;

  let y = 18;


  // ---------------------------------------------------------
  // HELPERS
  // ---------------------------------------------------------

  const checkPageBreak = (
    requiredHeight = 20
  ) => {
    if (
      y + requiredHeight >
      pageHeight - 22
    ) {
      pdf.addPage();

      y = 18;
    }
  };


  const addSectionTitle = (title) => {
    checkPageBreak(16);

    pdf.setFont(
      "helvetica",
      "bold"
    );

    pdf.setFontSize(13);

    pdf.setTextColor(
      30,
      64,
      175
    );

    pdf.text(
      title,
      margin,
      y
    );

    y += 8;
  };


  const addLabelValue = (
    label,
    value
  ) => {
    checkPageBreak(12);

    pdf.setFont(
      "helvetica",
      "normal"
    );

    pdf.setFontSize(10);

    pdf.setTextColor(
      100,
      116,
      139
    );

    pdf.text(
      label,
      margin,
      y
    );

    pdf.setFont(
      "helvetica",
      "bold"
    );

    pdf.setTextColor(
      15,
      23,
      42
    );

    pdf.text(
      String(value),
      margin + 58,
      y
    );

    y += 7;
  };


  // ---------------------------------------------------------
  // HEADER
  // ---------------------------------------------------------

  pdf.setFont(
    "helvetica",
    "bold"
  );

  pdf.setFontSize(20);

  pdf.setTextColor(
    15,
    23,
    42
  );

  pdf.text(
    "AI Medical Image Classifier",
    margin,
    y
  );

  y += 8;


  pdf.setFont(
    "helvetica",
    "normal"
  );

  pdf.setFontSize(10);

  pdf.setTextColor(
    100,
    116,
    139
  );

  pdf.text(
    "Academic Chest X-ray Classification Report",
    margin,
    y
  );

  y += 6;


  pdf.setDrawColor(
    226,
    232,
    240
  );

  pdf.line(
    margin,
    y,
    pageWidth - margin,
    y
  );

  y += 10;


  // ---------------------------------------------------------
  // REPORT INFORMATION
  // ---------------------------------------------------------

  addSectionTitle(
    "Report Information"
  );


  addLabelValue(
    "User Name",
    user?.full_name ||
      "Authenticated User"
  );


  addLabelValue(
    "Date & Time",
    new Date().toLocaleString()
  );


  addLabelValue(
    "Image Filename",
    selectedFile?.name ||
      prediction.image_filename ||
      "Unavailable"
  );


  addLabelValue(
    "Deployment Model",
    "DenseNet121"
  );


  y += 5;


  // ---------------------------------------------------------
  // X-RAY IMAGE
  // ---------------------------------------------------------

  addSectionTitle(
    "Uploaded Chest X-ray"
  );


  if (selectedFile) {
    try {
      const imageData =
        await loadImageAsDataUrl(
          selectedFile
        );

      const dimensions =
        await getImageDimensions(
          imageData,
          90,
          82
        );

      checkPageBreak(
        dimensions.height + 10
      );

      const imageX =
        margin +
        (
          contentWidth -
          dimensions.width
        ) /
          2;

      const imageFormat =
        selectedFile.type ===
        "image/png"
          ? "PNG"
          : "JPEG";

      pdf.addImage(
        imageData,
        imageFormat,
        imageX,
        y,
        dimensions.width,
        dimensions.height
      );

      y +=
        dimensions.height + 10;

    } catch (error) {
      pdf.setFontSize(10);

      pdf.setTextColor(
        185,
        28,
        28
      );

      pdf.text(
        "The uploaded image could not be added to the PDF.",
        margin,
        y
      );

      y += 8;
    }
  } else {
    pdf.setFontSize(10);

    pdf.setTextColor(
      100,
      116,
      139
    );

    pdf.text(
      "Uploaded X-ray image is not available.",
      margin,
      y
    );

    y += 8;
  }


  // ---------------------------------------------------------
  // CLASSIFICATION
  // ---------------------------------------------------------

  addSectionTitle(
    "AI Model Classification"
  );


  addLabelValue(
    "Predicted Class",
    formatClassName(
      prediction.predicted_class
    )
  );


  addLabelValue(
    "Model Confidence",
    `${Number(
      prediction.confidence || 0
    ).toFixed(2)}%`
  );


  y += 5;


  // ---------------------------------------------------------
  // CLASS PROBABILITIES
  // ---------------------------------------------------------

  addSectionTitle(
    "Class Probabilities"
  );


  const probabilities =
    prediction.probabilities || {};


  addLabelValue(
    "COVID-19",
    `${Number(
      probabilities.covid19 || 0
    ).toFixed(2)}%`
  );


  addLabelValue(
    "Normal",
    `${Number(
      probabilities.normal || 0
    ).toFixed(2)}%`
  );


  addLabelValue(
    "Pneumonia",
    `${Number(
      probabilities.pneumonia || 0
    ).toFixed(2)}%`
  );


  addLabelValue(
    "Tuberculosis",
    `${Number(
      probabilities.tuberculosis || 0
    ).toFixed(2)}%`
  );


  y += 5;


  // ---------------------------------------------------------
  // MODEL PERFORMANCE
  // ---------------------------------------------------------

  addSectionTitle(
    "DenseNet121 Test-set Performance"
  );


  addLabelValue(
    "Test Accuracy",
    "94.48%"
  );


  addLabelValue(
    "Macro Precision",
    "92.44%"
  );


  addLabelValue(
    "Macro Recall",
    "94.55%"
  );


  addLabelValue(
    "Macro F1-score",
    "93.33%"
  );


  checkPageBreak(18);


  pdf.setFont(
    "helvetica",
    "italic"
  );

  pdf.setFontSize(9);

  pdf.setTextColor(
    100,
    116,
    139
  );


  const metricNote =
    pdf.splitTextToSize(
      "These are precomputed evaluation metrics obtained on the held-out test dataset used in this project. They are not the confidence score for the uploaded image and do not establish clinical performance.",
      contentWidth
    );


  pdf.text(
    metricNote,
    margin,
    y
  );


  y +=
    metricNote.length * 4.5 + 8;


  // ---------------------------------------------------------
  // AI EXPLANATION
  // ---------------------------------------------------------

  addSectionTitle(
    "AI-Generated Explanation"
  );


  pdf.setFont(
    "helvetica",
    "normal"
  );

  pdf.setFontSize(10);

  pdf.setTextColor(
    71,
    85,
    105
  );


  const explanation =
    prediction.ai_summary ||
    "AI-generated explanation is unavailable for this prediction.";


  const explanationLines =
    pdf.splitTextToSize(
      explanation,
      contentWidth
    );


  for (
    const line of explanationLines
  ) {
    checkPageBreak(7);

    pdf.text(
      line,
      margin,
      y
    );

    y += 5;
  }


  y += 7;


  // ---------------------------------------------------------
  // PROJECT DISCLAIMER
  // ---------------------------------------------------------

  addSectionTitle(
    "Important Disclaimer"
  );


  pdf.setFont(
    "helvetica",
    "normal"
  );

  pdf.setFontSize(9.5);

  pdf.setTextColor(
    154,
    52,
    18
  );


  const disclaimerLines =
    pdf.splitTextToSize(
      DISCLAIMER,
      contentWidth
    );


  for (
    const line of disclaimerLines
  ) {
    checkPageBreak(6);

    pdf.text(
      line,
      margin,
      y
    );

    y += 5;
  }


  // ---------------------------------------------------------
  // FOOTER ON EVERY PAGE
  // ---------------------------------------------------------

  const totalPages =
    pdf.getNumberOfPages();


  for (
    let page = 1;
    page <= totalPages;
    page += 1
  ) {
    pdf.setPage(page);

    pdf.setDrawColor(
      226,
      232,
      240
    );

    pdf.line(
      margin,
      pageHeight - 15,
      pageWidth - margin,
      pageHeight - 15
    );


    pdf.setFont(
      "helvetica",
      "normal"
    );

    pdf.setFontSize(8);

    pdf.setTextColor(
      100,
      116,
      139
    );


    pdf.text(
      "Academic AI classification report - Not a medical diagnosis",
      margin,
      pageHeight - 9
    );


    pdf.text(
      `Page ${page} of ${totalPages}`,
      pageWidth - margin,
      pageHeight - 9,
      {
        align: "right",
      }
    );
  }


  // ---------------------------------------------------------
  // DOWNLOAD
  // ---------------------------------------------------------

  const className =
    prediction.predicted_class ||
    "classification";


  const safeClassName =
    className
      .toLowerCase()
      .replace(
        /[^a-z0-9]+/g,
        "_"
      );


  pdf.save(
    `AI_Medical_Report_${safeClassName}.pdf`
  );
};